### ISSUE TITLE
Error: TemplateDoesNotExist at rest_framework/api.html

### ISSUE THREAD

**Issue by kennethsn** [kennethsn/django-wikidata-api#2]
This error was reported when trying to access a model rest api framework prior to authentication:
```
TemplateDoesNotExist
rest_framework/api.html
```

**Comment by kennethsn** [comment]
This was resolved by changing the default rest framework settings in the app settings.p:
```
REST_FRAMEWORK = {
'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        # 'rest_framework.renderers.BrowsableAPIRenderer',  <- removing this
    ]
}
```

**Comment by pranita7878** [comment]
thank you so much

**Comment by mir4zul** [comment]
setting.py add rest_framework , if you don't add this rest_framework

INSTALLED_APPS = [
    "rest_framework",
]
